/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connection.JFLConnection;
import connection.PlayerConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 23356235
 */
public class JFLViewTeam extends javax.swing.JFrame {

    /**
     * Creates new form JFLViewTeam
     */
    public JFLViewTeam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboViewTeam = new javax.swing.JComboBox<>();
        btnLoad = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnretrieveTeam = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeletePlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("View Teams");

        jLabel2.setText("Team Name:");

        cboViewTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboViewTeamActionPerformed(evt);
            }
        });

        btnLoad.setText("Load Team");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnretrieveTeam.setText("Retrieve Teams");
        btnretrieveTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretrieveTeamActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach", "Manager"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Position"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnDeletePlayer.setText("Delete Player");
        btnDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHome)
                                .addGap(174, 174, 174))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnretrieveTeam)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboViewTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLoad)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeletePlayer)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnretrieveTeam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboViewTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoad)
                        .addComponent(btnDeletePlayer)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        new JFHome().setVisible(true);
        
    }//GEN-LAST:event_btnHomeActionPerformed
private void LoadTeam() {
    //Connect to Team database, and get TEAMNAMES. Add TEAMNAMES to cboViewTeam 
    ResultSet rs = null;
    PlayerConnection ac = new PlayerConnection("JFLTeam");
  final String retrieveQuery = "SELECT TEAMNAME from app.TEAM";
    ac.setQuery(retrieveQuery);
    ac.runQuery();
    DefaultComboBoxModel model =(DefaultComboBoxModel) cboViewTeam.getModel();
    ResultSet output = ac.getResultSet();
    
         try {   
              if (null != output)
              {
             while(output.next())
            {
                String Team = output.getString(1);
                cboViewTeam.addItem(Team);
            }
              }
    
                    }
    catch (SQLException sqle)
    {
        System.out.println("Expcetion while printing" + sqle.toString());
        }
}
private void LoadManager() {
    //Connect to Team database, and select COACH and MANAGER according to cboViewTeam. Add these to jTable2
    JFLConnection ac = new JFLConnection("JFLTeam");
    final String retrieveQuery = "SELECT COACH, MANAGER from app.TEAM where TEAMNAME = '" + cboViewTeam.getSelectedItem() + "'";
    ac.setQuery(retrieveQuery);
    ac.runQuery();
    DefaultTableModel model =(DefaultTableModel) jTable2.getModel();
    ResultSet output = ac.getResultSet();
    try
    {
        if (null != output)
        {
            while(output.next())
            {
                String cname = output.getString(1);
                String mname = output.getString(2);
                model.addRow(new Object[]{cname, mname});   
            }
        }
    
                    }
    catch (SQLException sqle)
    {
        System.out.println("Expcetion while printing" + sqle.toString());
        }
}
    private void insertRecords() {
        //Conect to PLAYERS database, and run SQL query selecting players according to their team. Add players to jTable1
     JFLConnection ac = new JFLConnection("JFLTeam");
    final String retrieveQuery = "SELECT PNAME, PLNAME, POSITION from app.PLAYERS where TEAM = '" + cboViewTeam.getSelectedItem() + "'";
            
    ac.setQuery(retrieveQuery);
    ac.runQuery();
    DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
    ResultSet output = ac.getResultSet();
    try
    {
        if (null != output)
        {
            while(output.next())
            {
                String fname = output.getString(1);
                String lname = output.getString(2);
                String position = output.getString(3);
                model.addRow(new Object[]{fname, lname, position});   
            }
        }
    
                    }
    catch (SQLException sqle)
    {
        System.out.println("Expcetion while printing" + sqle.toString());
        }
    }

    private void cboViewTeam() {
}
    private void cboViewTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboViewTeamActionPerformed

    }//GEN-LAST:event_cboViewTeamActionPerformed

    private void btnretrieveTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretrieveTeamActionPerformed
      //load teams into combobox
        LoadTeam();
    }//GEN-LAST:event_btnretrieveTeamActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
      //reset tables, then run insertRecords and LoadManager methods to populate tables
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
       model.setRowCount(0);
       model2.setRowCount(0);
        insertRecords();
        LoadManager();
    }//GEN-LAST:event_btnLoadActionPerformed
public void DeletePlayer() 
{
    //get selected player's last name from table, and add to query. Delete player record from Players table according to that query.
       int row = jTable1.getSelectedRow();
int column = jTable1.getSelectedColumn();
    final String cellValue = (String)jTable1.getValueAt(row, column);
    PlayerConnection ac = new PlayerConnection("JFLTeam");
     final String retrieveQuery = "DELETE FROM app.PLAYERS WHERE PLNAME = '" + cellValue + "'";
    ac.setQuery(retrieveQuery);
    ac.updateQuery();
}
    private void btnDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlayerActionPerformed
        //run DeletePlayer method
        DeletePlayer();
    }//GEN-LAST:event_btnDeletePlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLViewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLViewTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletePlayer;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnretrieveTeam;
    private javax.swing.JComboBox<String> cboViewTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
