/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import java.util.ArrayList;
import connection.StudentConnection;
import javax.swing.JOptionPane;
/**
 *
 * @author brend
 */
public class GStudent extends javax.swing.JFrame {
ArrayList<Student> ObjectList = new ArrayList<Student>(100);
    /**
     * Creates new form GStudent
     */
    public GStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudent = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtSNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        LRole = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LSkill = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGenerateTeam = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStudent.setText("Submit");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        LRole.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Specification", "Design", "Development", "Testing" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(LRole);

        LSkill.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Team Management", "Planning", "Programming", "Negotiation", "Design", "Writing a report", "Time Management", "Research", "Leadership" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(LSkill);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Student Number");

        jLabel4.setText("Role");

        jLabel5.setText("Skills");

        btnGenerateTeam.setText("Generate Groups");
        btnGenerateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTeamActionPerformed(evt);
            }
        });

        jLabel6.setText("Add Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFName)
                    .addComponent(txtSNumber))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txtSNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateTeam)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4)))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
    //Check if textboxes and lists have a value inputed / selected. If they haven't, throw up an error message
        if (txtFName.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Error! Please enter a value");
        
        } else if (txtLName.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Error! Please enter a value");
        } 
        else if (txtSNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Error! Please enter a value");
        }
        else if (LRole.getSelectedValue().equals("")) {
            JOptionPane.showMessageDialog(null,"Error! Please enter a value");
        }
        else if (LSkill.getSelectedValue().equals("")) {
            JOptionPane.showMessageDialog(null,"Error! Please enter a value");
        }
        else {
            //If every box has a value create a new Student object, and then add it to ObjectList list
              Student students = new Student(txtFName.getText(), txtLName.getText(), txtSNumber.getText(), LRole.getSelectedValue(), LSkill.getSelectedValue(), 0);
      ObjectList.add(students);
      System.out.print(ObjectList);
        String FName = txtFName.getText();
       String LName = txtLName.getText();
        String SNumber = txtSNumber.getText();
        String Role = LRole.getSelectedValue();
        String Skill = LSkill.getSelectedValue();
        }
                
     
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnGenerateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTeamActionPerformed
//Check if Objects from ObjectList match a role, and if their team value is 0 (Default, meaning unsorted)
  final int[] nextId = new int[]{01};
ObjectList.stream()
        .filter(s -> "Design".equals(s.getRole()) && s.getTeam() == 0)
        //count up as objects with specified role are sorted, so that each team has one of each role
        .forEach(s -> {
             s.setTeam(nextId[0]++);
              String DTeam = Integer.toString(s.Team);
              //print in console, and create a new StudentConnection object. Use this to enter modified objects into database
              System.out.println(DTeam);
              System.out.println(s);
              StudentConnection ac = new StudentConnection("Task5DB");
        ac.insertRecord(s.FName, s.LName, s.StudentNo, s.Role, s.Skills, s.Team);
        ac.closeConnection();
           
           });
         
               final int[] nextId1 = new int[]{01};
ObjectList.stream()
        .filter(s -> "Specification".equals(s.getRole()) && s.getTeam() == 0)
        .forEach(s -> {
             s.setTeam(nextId1[0]++);
             String DTeam = Integer.toString(s.Team);
              System.out.println(DTeam);
              System.out.println(s);
              StudentConnection ac = new StudentConnection("Task5DB");
        ac.insertRecord(s.FName, s.LName, s.StudentNo, s.Role, s.Skills, s.Team);
        ac.closeConnection();
           });

final int[] nextId2 = new int[]{01};
ObjectList.stream()
        .filter(s -> "Development".equals(s.getRole()) && s.getTeam() == 0)
        .forEach(s -> {
             s.setTeam(nextId2[0]++);
            String DTeam = Integer.toString(s.Team);
              System.out.println(DTeam);
              System.out.println(s);
              StudentConnection ac = new StudentConnection("Task5DB");
        ac.insertRecord(s.FName, s.LName, s.StudentNo, s.Role, s.Skills, s.Team);
        ac.closeConnection();
           });

final int[] nextId3 = new int[]{01};
ObjectList.stream()
        .filter(s -> "Testing".equals(s.getRole()) && s.getTeam() == 0)
        .forEach(s -> {
             s.setTeam(nextId3[0]++);
            String DTeam = Integer.toString(s.Team);
              System.out.println(DTeam);
              System.out.println(s);
              StudentConnection ac = new StudentConnection("Task5DB");
        ac.insertRecord(s.FName, s.LName, s.StudentNo, s.Role, s.Skills, s.Team);
        ac.closeConnection();
           });
    }//GEN-LAST:event_btnGenerateTeamActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
         this.setVisible(false);
            new GSHome().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed
    
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                new GStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LRole;
    private javax.swing.JList<String> LSkill;
    private javax.swing.JButton btnGenerateTeam;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSNumber;
    // End of variables declaration//GEN-END:variables
}
